language: python
install: bash ci/travis-setup.sh
before_script:
  - export PATH=/tmp/ci/ana/bin:$PATH
  - export JAVA_HOME=
  - export TMPDIR=/tmp
script:
  - source activate lcdb-wf-test && snakemake -prs references.snakefile --configfile config/test_config.yaml --use-conda -j2
  - source activate lcdb-wf-test && snakemake -prs rnaseq.snakefile --configfile config/test_config.yaml --use-conda -j2
  - source activate lcdb-wf-test && py.test wrappers/test -n2 -v
