language: python
install: bash ci/travis-setup.sh
before_script:
  - export PATH=/tmp/ci/ana/bin:$PATH
  - export JAVA_HOME=
  - export TMPDIR=/tmp
script:
  - ci/travis-run.sh
env:
  global:
    - ENCRYPTION_LABEL: "27b4c1eaf7da"

matrix:
  include:
    - env: TYPE=rnaseq.snakefile
    - env: TYPE=references.snakefile
    - env: TYPE=pytest
    - env: TYPE=docs
