language: python
install: bash ci/travis-setup.sh
before_script:
  - export PATH=/tmp/ci/ana/bin:$PATH
  - export JAVA_HOME=
  - export TMPDIR=/tmp
script:
  - ci/travis-run.sh
  - ci/build-docs.sh
env:
  - TYPE=rnaseq.snakefile
  - TYPE=references.snakefile
  - TYPE=pytest
  - global:
      - ENCRYPTION_LABEL: "27b4c1eaf7da"

