language: python
install: bash ci/travis-setup.sh
before_script:
  - export PATH=$HOME/anaconda/bin:$PATH
  - export JAVA_HOME=
  - export TMPDIR=/tmp
script:
  - snakemake -prs rnaseq.snakefile --configfile config/test_config.yaml --use-conda -j1
  - py.test wrappers/test -v
