language: python
install: bash travis-setup.sh
before_script:
  - export PATH=$HOME/anaconda/bin:$PATH
  - export JAVA_HOME=
script: snakemake -prs rnaseq.snakefile --configfile test_config.yaml --use-conda -j1
