channels:
  - bioconda
  - conda-forge
  - r

dependencies:
  - bioconductor-deseq2
  - bioconductor-org.hs.eg.db
  - bioconductor-org.dm.eg.db
  - bioconductor-org.mm.eg.db
  - bioconductor-genomicfeatures
  - bioconductor-tximport
  - r-rmarkdown
  - pandoc
  - r-knitrbootstrap
  - r-knitr
  - r-pheatmap
  - r-readr
  - r-dt
