steps:
  -
    label: setup
    command: bash ci/travis-setup.sh
    artifact_paths:
      - setup.log
  -
    label: wrappers
    command: source $HOME/anaconda/bin/activate lcdb-wf-test && pytest wrappers/test -v
  -
    label: rnaseq
    command: source $HOME/anaconda/bin/activate lcdb-wf-test && snakemake -prs rnaseq.snakefile --configfile config/test_config.yaml --use-conda -j6
