steps:
  -
    label: setup
    command: bash ci/travis-setup.sh
    artifact_paths:
      - setup.log
  -
    label: wrappers
    command: source /opt/ci/miniconda/bin/activate lcdb-wf-test && pytest wrappers/test -v
